spring.application.name=wishlist
spring.datasource.url=jdbc:postgresql://localhost:5432/wishlist_db
spring.datasource.username=postgres
spring.datasource.password=7530
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true